export const signalWords: string[] = [
  "SOC Analyst",
  "Threat Hunting",
  "MITRE ATT&CK",
  "Incident Response",
  "Detection Engineering",
  "SIEM",
  "Zero Trust",
  "Cloud Security",
  "Cloud Hardening",
  "Security Automation",
  "Purple Teaming",
  "Vulnerability Management",
  "SOAR",
  "EDR",
  "Blue Team",
  "Kill Chain",
  "Observability",
  "DevSecOps",
  "Hardening",
  "Forensics",
];
